name: habitism
description: Habitism helps you manage habits along with daily tasks
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.6.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  built_collection: ^4.3.2
  built_value: ^7.1.0

  cupertino_icons: ^0.1.3
  emojis: ^0.8.1

dev_dependencies:
  build_runner: ^1.10.0
  built_value_generator: ^7.1.0
  pedantic: ^1.9.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
